const page1Content = `
<p style="line-height: 1.38; text-align: center; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">MUSIC ROOM REPORT</span></strong></p>
<p><br /><br /></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">OVERALL GOAL:</span></strong></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Analyze and understand the behavior of the inhabitants of the &lsquo;Music Room&rsquo; in order to better prepare team contingency plans against them, as well as sort it correctly for archiving purposes.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">EXPERIMENT ONE:</span></strong></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">GOAL: </span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Observe how the anomaly responds to survival stimuli.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">TEST ADMINISTERED</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: A plate of several items was left on its floor. The foods selected were:&nbsp;</span></p>
<ul style="margin-top: 0; margin-bottom: 0; padding-inline-start: 48px;">
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">an apple.&nbsp;</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A plate of fries.&nbsp;</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Toasted bread.&nbsp;</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A cupcake.&nbsp;</span></li>
</ul>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A camera was deployed to monitor the determined spot.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">RESULTS</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: After a short while, two subjects, denominated A-U-111-A and A-U-111-B, emerged from a car nearby.&nbsp;</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111-A chose the toasted bread.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111-B chose the apple.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111 chose to share the plate of fries.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111-A and A-U-111-B both reached for the cupcake, at which point they both froze in place. After three minutes, A-U-111-B ate the cupcake.</span></p>
<p><br /><br /></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">CONCLUSION</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: A-U-111 appears to be composed of two people, although for the purposes of identifying the phonomenon, the team chose to stick with one general tag. A-U-111 appears capable of sharing and settling disputes with itself, and each person appears to have preferences.</span></p>
<p><br /><br /></p>

`

const page2Content = `
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">EXPERIMENT TWO:</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">GOAL</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: Observe how the anomaly responds to environmental stimuli.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">TEST ADMINISTERED</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: T-R4 was tasked with dusting off a portion of the area, clearing it from debris and setting some lighting. T-R2 had the idea of placing down a rug to make the spot look more lively.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">RESULTS</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: A-U-111 moved to the spot almost immediately after , hauling a piano and a trumpet. A-U-111 left the spot, then came back pushing a car-- it was then left close to the rug spot. The Information team found it inadvisable to retrieve the rug.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">CONCLUSION: </span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111 responds well to a clean environment, and willingly migrates to it as soon as it notices its existence. Furthermore, A-U-111 is capable of experiencing fatigue, as they appear to potentially rest inside of the cars&hellip; potentially for more comfort?</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We need a new rug.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">EXPERIMENT THREE:&nbsp;</span></strong></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">GOAL</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: Observe how the anomaly responds to social stimuli.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">TEST ADMINISTERED ONE</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: T-R2 went down to deploy a handheld transceiver, which they then placed onto the rug in clear view. T-R1 was to create rapport with the anomaly through the device.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">RESULTS</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: A-U-111 stared blankly at the transceiver. When it began to make noise, A-U-111-A stomped onto the walkie, breaking it.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">TEST ADMINISTERED TWO</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: T-R1 was sent down to talk with A-U-111 directly. Protective headgear was provided in the case of aggression.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">RESULTS</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: T-R1 was unsuccessful in communicating with A-U-111, as it failed to respond to any queries. After three minutes, A-U-111-B began to play its song. T-R1 was extracted immediately and the experiment ceased.</span></p>
<p>&nbsp;</p>

`

const page3Content = `
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">T-R1 aged a rough guess of seven years in the span that it took to take them out. Their body aged appropriately, and their hair and nails grew to the appropriate length they would have in that amount of time, which led to a staggering 3 &frac12; feet of hair. Conditions reported were remembering things that had not happened, as well as auditory hallucinations of those memories. When exposed to a recording of the piano section for around the same length, these symptoms withdrew.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">CONCLUSION</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: Undetermined. A-U-111 did not appear hostile, although after what happened with T-R1, it is probably safe to say approaching A-U-111 is ill-advised. T-R1 seems to have had some sort of epiphany about that look, though, but that is more likely to be a &lsquo;them&rsquo; problem.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">EXPERIMENT FOUR</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">:&nbsp;</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">GOAL: </span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Determine how the anomaly responds to behavior correction.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">TEST ADMINISTERED ONE: </span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I-R3 was sent down with a pair of protective headgear to seize the instruments.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">RESULTS</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: A-U-111 became enraged, and from it emerged what I-R3 described as &lsquo;the worst noise i&rsquo;ve heard in my entire life&rsquo;, although the recording device could not pick up the frequency. After he was pulled out, I-R3 reported a hypersensitivity to sounds, and if anyone else in the team &lsquo;heard that song that&rsquo;s always playing&rsquo;. Furthermore, I-R3 felt a need to recreate the song in their head, gravitating towards instruments. In an attempt to fix this, a recording of the piano section was played again. While it succeeded in fixing the infohazard, it did not fix the sudden obsession with the song. This is likely to continue until the end of the loop.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">TEST ADMINISTERED TWO</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: T-R5 went down in order to ask them to cease playing. Touching it or its instruments was prohibited.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">RESULTS</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">: Once firmly asked, A-U-111-A ceased playing, while A-U-111-B was slower on the uptick. T-R5 did not age significantly from the delayed reaction. However, A-U-111 refused to communicate further.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">CONCLUSION:</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> Aggressive behavior correction will cause A-U-111 to turn hostile. Meanwhile, firm, steady behavioral correction will cause A-U-111 to cease its song. The anomaly is reticent to talk, but it can understand commands.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">---</span></p>
<p>&nbsp;</p>

`

const page4Content = `
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">EXPERIMENT FIVE:</span></strong></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">GOAL:</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> Further evaluate if each individual unit of A-U-111 can communicate and/or express preferences.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">TEST ADMINISTERED ONE:</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> T-R5 prepared a series of images in pairs, which were shown to A-U-111. It was then asked to pick between concepts. The concepts shown were:</span></p>
<p>&nbsp;</p>
<ul style="margin-top: 0; margin-bottom: 0; padding-inline-start: 48px;">
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Red or Blue</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Hot or Cold</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Up or Down</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Sweet or Sour</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Light or Darkness</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Tight or Vast</span></li>
</ul>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Furthermore, a series of more value-based concepts were prepared. These were:</span></p>
<ul style="margin-top: 0; margin-bottom: 0; padding-inline-start: 48px;">
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Life or Death</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Attack or Protect</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Past or Future</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">War or Peace</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Me or Us</span></li>
</ul>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">RESULTS:</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> A-U-111 remembered T-R5&rsquo;s request to cease playing and honored it as soon as it became aware of them. Upon asked, A-U-111 showed the following preferences:</span></p>
<p>&nbsp;</p>
<ul style="margin-top: 0; margin-bottom: 0; padding-inline-start: 48px;">
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111-A chose Red, where A-U-111-B chose Blue;</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111-A chose Hot, where A-U-111-B Cold;</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111 chose Up;</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111-B chose Sweet, A-U-111-A did not choose, but when prompted, also chose Sweet;</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111 chose Light;</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111 showed no preference between Tight and Vast;</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111 chose Life;</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111-B chose to Protect, A-U-111-A chose to Attack;</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111-A chose Past, A-U-111-B chose Future;</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111 showed no preference between War and Peace;</span></li>
<li aria-level="1"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111 became agitated at Me or Us, at which point it refused to respond.</span></li>
</ul>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">CONCLUSION: </span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A-U-111 appear to agree on some things and completely disagree on other subjects. Questions about individuality versus the whole triggers discomfort in it, but not enough to immediately cause harm.</span></p>

`;

const page5Content = `
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">TEST ADMINISTERED TWO:</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> T-R5 returned with the following series of questions on a piece of paper:</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Can you speak?</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">What day is it?</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">How do you feel?</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Where did you come from?</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Do you like the rug?</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Do you sleep?</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Do you like to play music?</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">What am I to you?</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Can we speak again?</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">RESULTS:</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> A-U-111 once again ceased playing as soon as T-R5 became visible. It took turns writing on the notebook, answering as seen below:</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Can you speak? </span><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Yes</span></strong></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">What day is it? </span><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">[Left blank]</span></strong></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">How do you feel? </span><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">[Left blank]</span></strong></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Where did you come from? </span><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Down there</span></strong></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Do you like the rug? </span><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Yes</span></strong></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Do you sleep? </span><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Yes</span></strong></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Do you like to play music? </span><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Yes</span></strong></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">What am I to you? </span><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Employee</span></strong></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Can we speak again? </span><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Okay</span></strong></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">CONCLUSION:</span></strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> Either A-U-111 is deluded that EVERYONE is an employee, or it has correctly identified T-R5 as a previous worker. More research is needed on this front. As for everything else, it answers in unison with no discussion. As expected, it does not know where it is, but it claims to be from &lsquo;down there&rsquo;. Further in the parking lot? The company?</span></p>


`;

const page6Content = `
<p><br /><br /></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">FINAL EVALUATION:</span></strong></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We don&rsquo;t have nearly enough information to deal with whatever this is, even after all these tests. Toying with it is going to be a problem-- it&rsquo;s already safely contained in that parking lot, so why bother?&nbsp;</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">And yet, Camille is dead set that we should &lsquo;train&rsquo; this thing. She could use the lesson that not everything needs re-purposing, and if it&rsquo;s her agents getting tossed around time, then let that be it. Either way, they sure as hell are from the corp, as Parker suggested. I don&rsquo;t know what kind of senseless horrors they were put through, but I don&rsquo;t think I want to find out if it left them in this state.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Alas, I can&rsquo;t deny not having it escape at one point without us knowing anything on how to suppress it would be extremely beneficial. More tests it is.</span></p>
<p><br /><br /></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: 'IBM Plex Sans',sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">-Vik</span></p>

`;


class Page {
  number;
  content;
  constructor(number, content){
    this.number = number;
    this.content = content;
  }

  render = (ele)=>{
    //make a div, add to parent, add dirt graphics.
    const me = document.createElement("div");
    me.className =(`page`);
    me.innerHTML = this.content;
    const bg = document.createElement("div");
    bg.className=`page${this.number}`;
    me.append(bg)
    ele.append(me);
  }
}

